Fix build on Mac/clang:
In file included from ../CC/geant4.C:15:
23-Feb-2015 15:43:22	../include/daqevt.h:105:62: error: field '_pgetlength' will be initialized after field '_id' [-Werror,-Wreorder]
23-Feb-2015 15:43:22	  DAQBlockType():_maxbl(0),_plength(0),_pgmb(0),_pgetdata(0),_pgetlength(0),_id(),_next(){}
23-Feb-2015 15:43:22	                                                             ^
23-Feb-2015 15:43:22	../include/daqevt.h:106:124: error: field '_pgetlength' will be initialized after field '_id' [-Werror,-Wreorder]
23-Feb-2015 15:43:22	  DAQBlockType(pgetmaxblocks pgmb, pgetl pgl, pgetdata pget, integer id):_maxbl(0),_plength(0),_pgmb(pgmb),_pgetdata(pget),_pgetlength(pgl),_id(id),_next(){}

Reorder, so that _id is initialized first. Then also set it to 0 in the default constructor, not to nothing (aka. unitialized memory).